export let table = {
  tableName: 'vehicleknowledge',
  comment: '',
  comments: '车型知识库',
  sfsh: '否',
  authPeople: '否',
  emailRegister: '否',
  detail: '是',
  foreEndList: '否',
  foreEndAdd: '否',
  jifen: '否',
  isReverse: '否',
  hasCart: '否',
  limit: '否',
  mulGraphType: '',
  virtualPay: '否',
  hasSales: false,
  vip: '否',
  groupBuy: '否',
  creditScore: '否',
  authSeparate: '否',
  tplist: '否',
  addHomePage: '否',
  hasPay: '否',
  hasAlipay: '否',
  hasRegister: '否',
  thumbsUp: '否',
  discuss: '否',
  storeUp: '否',
  statistics: '',
  mulStatistics: '',
  selectSeat: '否',
  menuJump: '列表',
  browseClick: '否',
  browseHistory: '否',
  foreEndListAuth: '否',
  location: '否',
  isAdmin: '否',
  sessionReadTable: '',
  merchantRole: '',
  exportExcel: '否',
  importExcel: '否',
  hasPrint: '否',
  frontLogin: '否',
  frontRegister: '否',
  backLogin: '否',
  backRegister: '否',
  homeSearch: '否',
  mapType: '无',
  homeStatistic: '无',
  passwordProtected: '否',
  tabBar: '否',
  hasChapter: '无',
  hasAuction: '否',
  hasHot: '无',
  hasMusic: '否',
  sharePlatform: '',
  hasChat: '无',
  collaborativeAction: '',
  fkMainTable: '',
  fixedAuth: '',
  passwordWrongNum: '0',
  buttons: '',
  imagePath: '',
  orderNum: '',
  status: '',
  conflictType: '',
  sortName: 'crawltime',
  sortOrder: 'desc',
  titleName: '',
  couponType: '',
  crossOptTableName: [],
  crossOptButton: [],
  crossOptAudit: [],
  crossOptPay: [],
  crossOptButtonStatusColumns: [],
  crossOptButtonTips: [],
  csuOperateList: [],
  csuTypeList: [],
  csuUpdateTableList: [],
  csuUpdateColumnList: [],
  csuUpdateColumnTypeList: [],
  csuUpdateColumnValueList: [],
  csuMessageList: [],
  csuConditionColumnList_1: [],
  csuConditionColumnList_2: [],
}

export let columns = [
  {
    columnName: 'vehiclemodel',
    comments: '车型名称',
    type: '普',
    hiden: '',
    form_type: 'YyText',
    form_hidden: false,
    options: [],
  },
  {
    columnName: 'manufacturer',
    comments: '厂商/品牌',
    type: '普',
    hiden: '',
    form_type: 'YyText',
    form_hidden: false,
    options: [],
  },
  {
    columnName: 'batterytype',
    comments: '电池类型',
    type: '普',
    hiden: '',
    form_type: 'YyText',
    form_hidden: false,
    options: [],
  },
  {
    columnName: 'officialrange',
    comments: '官方续航',
    type: '普',
    hiden: '',
    form_type: 'YyText',
    form_hidden: false,
    options: [],
  },
  {
    columnName: 'chargeinfo',
    comments: '充电信息',
    type: '普',
    hiden: '',
    form_type: 'YyText',
    form_hidden: false,
    options: [],
  },
  {
    columnName: 'summary',
    comments: '车型简介',
    type: '大文本',
    hiden: '',
    form_type: 'YyTextarea',
    form_hidden: false,
    options: [],
  },
  {
    columnName: 'sourceurl',
    comments: '来源地址',
    type: '大文本',
    hiden: '',
    form_type: 'YyTextarea',
    form_hidden: false,
    options: [],
  },
  {
    columnName: 'crawlstatus',
    comments: '采集状态',
    type: '普',
    hiden: '',
    form_type: 'YyText',
    form_hidden: false,
    options: [],
  },
  {
    columnName: 'crawltime',
    comments: '采集时间',
    type: '时间',
    hiden: '',
    form_type: 'YyDateTime',
    form_hidden: false,
    options: [],
  },
  {
    columnName: 'rawdata',
    comments: '原始数据',
    type: '大文本',
    hiden: '',
    form_type: 'YyTextarea',
    form_hidden: false,
    options: [],
  },
]

export let searchColumns = [
  {
    queryFlagInput: ['是'],
    columnName: 'vehiclemodel',
    comments: '车型名称',
    level: 0,
    refTable: '',
    refColumn: '',
    placeholder: '车型名称',
    form_type: 'YyText',
    options: [],
  },
  {
    queryFlagInput: ['是'],
    columnName: 'manufacturer',
    comments: '厂商/品牌',
    level: 0,
    refTable: '',
    refColumn: '',
    placeholder: '厂商/品牌',
    form_type: 'YyText',
    options: [],
  },
  {
    queryFlagInput: ['是'],
    columnName: 'crawlstatus',
    comments: '采集状态',
    level: 0,
    refTable: '',
    refColumn: '',
    placeholder: '采集状态',
    form_type: 'YyText',
    options: [],
  },
]

export let headerButtons = [
  {
    title: '新增',
    name: '新增',
    key: 'add',
    iconName: 'Plus',
    className: 'action-add',
  },
  {
    title: '批量采集',
    name: '批量采集',
    key: 'crawlVehicleKnowledgeBatch',
    iconName: 'Refresh',
    className: 'action-edit',
    isPublic: true,
  },
  {
    title: '删除',
    name: '删除',
    key: 'removes',
    iconName: 'Delete',
    className: 'action-removes',
  },
]

export let tableButtons = [
  {
    title: '重新采集',
    name: '重新采集',
    key: 'crawlVehicleKnowledge',
    iconName: 'Refresh',
    className: 'action-edit',
    isPublic: true,
  },
  {
    title: '查看',
    name: '查看',
    key: 'view',
    iconName: 'View',
    className: 'action-view',
  },
  {
    title: '修改',
    name: '修改',
    key: 'edit',
    className: 'action-edit',
    iconName: 'Edit',
  },
  {
    title: '删除',
    name: '删除',
    className: 'action-delete',
    key: 'remove',
    iconName: 'Delete',
  },
]

export let timeTable = {
  titleNames: [],
  subTitleNames: [],
  searchNames: [],
}
