[sql]
;support two sql,mysql and mssql,choice one
type = mysql
host = 127.0.0.1
port = 3306
user = root
passwd = 123456
db = diandong5k56la1f
; 推荐统一使用 utf8mb4，避免中文/特殊字符兼容问题
charset = utf8mb4
hasHadoop=spark
[redis]
host = 127.0.0.1
port = 6379
passwd = 123456
