
const chartData = [
  {
    tableName: 'drivinglog',  
    xColumn: 'batterycapacity',  
    api: 'drivinglog/sectionStat/batterycapacity',  
    graphType: '竖',  
    showHome: true,
    title: '电池容量分析',  
    subNameList: [],  
    type: 'multiStatic',  
    typeSections: ['40以下','41到60','60到100','100以上'],  
    hasMultiSeries: false,
    chartSort: '1',  
    func: '',  
    queryName: '',  
    queryRoles: [],  
  },
  {
    tableName: 'drivinglog',  
    xColumn: 'batterylife',  
    api: 'drivinglog/sectionStat/batterylife',  
    graphType: '横',  
    showHome: true,
    title: '电池寿命',  
    subNameList: [],  
    type: 'multiStatic',  
    typeSections: ['50以下','51到100','101至150','151以上'],  
    hasMultiSeries: false,
    chartSort: '2',  
    func: '',  
    queryName: '',  
    queryRoles: [],  
  },
  {
    tableName: 'drivinglog',  
    xColumn: 'drivingroute',  
    api: 'drivinglog/group/drivingroute',  
    graphType: '饼',  
    showHome: true,
    title: '路线分布',  
    subNameList: [],  
    type: 'multiStatic',  
    typeSections: [],  
    hasMultiSeries: false,
    chartSort: '3',  
    func: '',  
    queryName: '',  
    queryRoles: [],  
  },
  {
    tableName: 'drivinglog',  
    xColumn: 'drivingbehaviorrating',  
    api: 'drivinglog/sectionStat/drivingbehaviorrating',  
    graphType: '漏',  
    showHome: true,
    title: '驾驶评分',  
    subNameList: [],  
    type: 'multiStatic',  
    typeSections: ['20以下','31到60','60到100'],  
    hasMultiSeries: false,
    chartSort: '4',  
    func: '',  
    queryName: '',  
    queryRoles: [],  
  },
  {
    tableName: 'drivinglog',  
    xColumn: 'energysavingsuggestions',  
    api: 'wordCloud/drivinglog/energysavingsuggestions',  
    graphType: '词云',  
    showHome: true,
    title: '节能建议',  
    subNameList: [],  
    type: 'multiStatic',  
    typeSections: [],  
    hasMultiSeries: false,
    chartSort: '5',  
    func: '',  
    queryName: '',  
    queryRoles: [],  
  },
]
export default chartData