export let table = {
  tableName: 'discussdrivinglog',
  comment: '',
  comments: '评论反馈',
  sfsh: '否',
  authPeople: '否',
  emailRegister: '否',
  detail: '是',
  foreEndList: '否',
  foreEndAdd: '否',
  jifen: '否',
  isReverse: '否',
  hasCart: '否',
  limit: '否',
  mulGraphType: '',
  virtualPay: '否',
  hasSales: false,
  vip: '否',
  groupBuy: '否',
  creditScore: '否',
  authSeparate: '否',
  tplist: '否',
  addHomePage: '否',
  hasPay: '否',
  hasAlipay: '否',
  hasRegister: '否',
  thumbsUp: '否',
  discuss: '否',
  storeUp: '否',
  statistics: '',
  mulStatistics: '',
  selectSeat: '否',
  menuJump: '列表',
  browseClick: '否',
  browseHistory: '否',
  foreEndListAuth: '否',
  location: '否',
  isAdmin: '否',
  sessionReadTable: '',
  merchantRole: '',
  exportExcel: '否',
  importExcel: '否',
  hasPrint: '否',
  frontLogin: '否',
  frontRegister: '否',
  backLogin: '否',
  backRegister: '否',
  homeSearch: '否',
  mapType: '无',
  homeStatistic: '无',
  passwordProtected: '否',
  tabBar: '否',
  hasChapter: '无',
  hasAuction: '否',
  hasHot: '无',
  hasMusic: '否',
  sharePlatform: '',
  hasChat: '无',
  collaborativeAction: '',
  fkMainTable: '',
  fixedAuth: '',
  passwordWrongNum: '0',
  buttons: '',
  imagePath: '',
  orderNum: '',
  status: '',
  conflictType: '',
  sortName: 'addtime',
  sortOrder: 'desc',
  titleName: '',
  couponType: '',
  crossOptTableName: [],
  crossOptButton: [],
  crossOptAudit: [],
  crossOptPay: [],
  crossOptButtonStatusColumns: [],
  crossOptButtonTips: [],
  csuOperateList: [],
  csuTypeList: [],
  csuUpdateTableList: [],
  csuUpdateColumnList: [],
  csuUpdateColumnTypeList: [],
  csuUpdateColumnValueList: [],
  csuMessageList: [],
  csuConditionColumnList_1: [],
  csuConditionColumnList_2: [],
}

export let columns = [
  {
    columnName: 'nickname',
    comments: '评论用户',
    type: '普',
    hiden: '6',
    form_type: 'YyText',
    form_hidden: false,
    options: [],
  },
  {
    columnName: 'content',
    comments: '评论内容',
    type: '大文本',
    hiden: '',
    form_type: 'YyTextarea',
    form_hidden: false,
    options: [],
  },
  {
    columnName: 'reply',
    comments: '回复记录',
    type: '大文本',
    hiden: '6',
    form_type: 'YyTextarea',
    form_hidden: false,
    options: [],
  },
  {
    columnName: 'status',
    comments: '状态',
    type: '普',
    hiden: '6',
    form_type: 'YyText',
    form_hidden: false,
    options: [],
  },
]

export let searchColumns = [
  {
    queryFlagInput: ['是'],
    columnName: 'nickname',
    comments: '评论用户',
    level: 0,
    refTable: '',
    refColumn: '',
    placeholder: '评论用户',
    form_type: 'YyText',
    options: [],
  },
]

export let headerButtons = [
  {
    title: '新增',
    name: '新增',
    key: 'add',
    iconName: 'Plus',
    className: 'action-add',
  },
  {
    title: '删除',
    name: '删除',
    key: 'removes',
    iconName: 'Delete',
    className: 'action-removes',
  },
]

export let tableButtons = [
  {
    title: '查看',
    name: '查看',
    key: 'view',
    iconName: 'View',
    className: 'action-view',
  },
  {
    title: '回复',
    name: '修改',
    key: 'discussReply',
    iconName: 'ChatLineRound',
    className: 'action-edit',
  },
  {
    title: '删除',
    name: '删除',
    key: 'remove',
    className: 'action-delete',
    iconName: 'Delete',
  },
]

export let timeTable = {
  titleNames: [],
  subTitleNames: [],
  searchNames: [],
}
