export let table = {
  tableName: 'drivinglogforecast',
  comment: '',
  comments: '电池寿命预测',
  sfsh: '否',
  authPeople: '否',
  emailRegister: '否',
  detail: '否',
  foreEndList: '否',
  foreEndAdd: '否',
  jifen: '否',
  isReverse: '否',
  hasCart: '否',
  limit: '否',
  mulGraphType: '',
  virtualPay: '否',
  hasSales: false,
  vip: '否',
  groupBuy: '否',
  creditScore: '否',
  authSeparate: '否',
  tplist: '否',
  addHomePage: '否',
  hasPay: '否',
  hasAlipay: '否',
  hasRegister: '否',
  thumbsUp: '否',
  discuss: '否',
  storeUp: '否',
  statistics: '',
  mulStatistics: '',
  selectSeat: '否',
  menuJump: '列表',
  browseClick: '否',
  browseHistory: '否',
  foreEndListAuth: '否',
  location: '否',
  isAdmin: '否',
  sessionReadTable: '',
  merchantRole: '',
  exportExcel: '否',
  importExcel: '否',
  hasPrint: '否',
  frontLogin: '否',
  frontRegister: '否',
  backLogin: '否',
  backRegister: '否',
  homeSearch: '否',
  mapType: '无',
  homeStatistic: '无',
  passwordProtected: '否',
  tabBar: '否',
  hasChapter: '无',
  hasAuction: '否',
  hasHot: '无',
  hasMusic: '否',
  sharePlatform: '',
  hasChat: '无',
  collaborativeAction: '',
  fkMainTable: '',
  fixedAuth: '',
  passwordWrongNum: '0',
  buttons: '',
  imagePath: '',
  orderNum: '',
  status: '',
  conflictType: '',
  sortName: '',
  sortOrder: 'desc',
  titleName: '',
  couponType: '',

  crossOptTableName: [],
  crossOptButton: [],
  crossOptAudit: [],
  crossOptPay: [],
  crossOptButtonStatusColumns: [],
  crossOptButtonTips: [],

  csuOperateList: [],
  csuTypeList: [],
  csuUpdateTableList: [],
  csuUpdateColumnList: [],
  csuUpdateColumnTypeList: [],
  csuUpdateColumnValueList: [],
  csuMessageList: [],
  csuConditionColumnList_1: [],  
  csuConditionColumnList_2: [],
}


export let columns = [
  {
    columnName: 'vehiclemodel',
    comments: '车辆型号',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'batterycapacity',
    comments: '电池容量',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '数',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '0',
    form_type: 'YyTextNumber',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'accumulatedmileage',
    comments: '累计行驶里程',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '数',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '0',
    form_type: 'YyTextNumber',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'drivingbehaviorrating',
    comments: '驾驶行为评分',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '数',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '0',
    form_type: 'YyTextNumber',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'batterylife',
    comments: '电池寿命',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '数',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '0',
    form_type: 'YyTextNumber',  
    form_hidden: false,    
    options: [],
  },
]

export let searchColumns = [
  {
    queryFlagInput: ['是'],
    columnName: 'vehiclemodel',
    comments: '车辆型号',
    level: 0,
    refTable: '',
    refColumn: '',
    placeholder: '车辆型号',
    form_type: 'YyText', 
    options: [],
  },
]
export let headerButtons = [
  {
    title: '新增',
    name: '新增',
    key: 'add',
    iconName: 'Plus',
    className: 'action-add',
  },
  {
    title: '删除',
    name: '删除',
    key: 'removes',
    iconName: 'Delete',
    className: 'action-removes',
  },
  {
    title: '预测图表',
    name: '预测',
    key: 'forecastChart',
    iconName: 'DataAnalysis',
  },
]
export let tableButtons = [
  {
    title: '查看',
    name: '查看',
    key: 'view',
    iconName: 'View',
    className: 'action-view',
  },
  {
    title: '删除',
    name: '删除',
    key: 'remove',
    className: 'action-delete',
    iconName: 'Delete',
  },
  {
    title: '修改', 
    name: '修改',
    key: 'edit',
    className: 'action-edit',
    iconName: 'Edit',
  },

  {
    title:  '预测' ,
    name: '预测',
    key: 'forecast',
    predictionChValueColumns: 'vehiclemodel,batterycapacity,accumulatedmileage,drivingbehaviorrating',
    iconName: 'Pointer',
  },
]

/**
 * @description 用权
 * titleNames: 标题
 * subTitleNames: 副标题
 * searchNames: 用权。显示的时候，根据这个条件过滤
 */ 
export let timeTable = {
  titleNames: [],
  subTitleNames: [],
  searchNames: []
}